# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cafenow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcafenow.proto\x12\x0c\x63\x61\x66\x65now.grpc\",\n\x07\x42\x61sicVO\x12\x10\n\x08\x61pi_type\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2O\n\x0c\x43\x61\x66\x65nowAgent\x12?\n\rhandleProcess\x12\x15.cafenow.grpc.BasicVO\x1a\x15.cafenow.grpc.BasicVO\"\x00\x62\x06proto3')



_BASICVO = DESCRIPTOR.message_types_by_name['BasicVO']
BasicVO = _reflection.GeneratedProtocolMessageType('BasicVO', (_message.Message,), {
  'DESCRIPTOR' : _BASICVO,
  '__module__' : 'cafenow_pb2'
  # @@protoc_insertion_point(class_scope:cafenow.grpc.BasicVO)
  })
_sym_db.RegisterMessage(BasicVO)

_CAFENOWAGENT = DESCRIPTOR.services_by_name['CafenowAgent']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASICVO._serialized_start=31
  _BASICVO._serialized_end=75
  _CAFENOWAGENT._serialized_start=77
  _CAFENOWAGENT._serialized_end=156
# @@protoc_insertion_point(module_scope)
